name: movie
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  flutter_bloc:

  # Utils
  mutex: ^3.0.1
  logger: ^2.0.2+1
  device_info_plus: ^9.1.1
  permission_handler: ^11.0.1
  envied: ^0.5.2
  toastification: ^1.1.0

  # Dependency Managers
  get_it: ^7.6.4

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # Database
  shared_preferences: ^2.2.1
  equatable: ^2.0.5

  # Animations
  loading_animation_widget: ^1.2.0+4
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  freezed_annotation: ^2.4.1
  file_picker: ^6.1.1
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  dartz: ^0.10.1
  connectivity_plus: ^5.0.2
  sembast: ^3.5.0+1
  path_provider: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_flavorizr: ^2.2.1
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  envied_generator: ^0.5.2

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
